// Field definitions: Financial, Web3
// Extracted from field-registry.ts to reduce file size

// ─── Financial Fields ────────────────────────────────────────────────────────

export const FINANCIAL_FIELDS = {
  "currency-amount": {
    id: "currency-amount",
    category: "financial" as const,
    label: "Amount (USD)",
    icon: "💲",
    placeholder: "0.00",
    description: "Dollar amount",
    inputType: "number" as const,
    prefix: "$",
    validation: { pattern: "^\\d+\\.?\\d{0,2}$" },
    color: {
      border: "border-green-400/50",
      bg: "bg-green-400/10",
      text: "text-green-400",
      glow: "shadow-[0_0_16px_rgba(74,222,128,0.2)]",
    },
  },
  percentage: {
    id: "percentage",
    category: "financial" as const,
    label: "Percentage",
    icon: "%",
    placeholder: "0.00",
    description: "Percentage value",
    inputType: "number" as const,
    validation: { pattern: "^\\d+\\.?\\d{0,4}$" },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "bank-account": {
    id: "bank-account",
    category: "financial" as const,
    label: "Bank Account",
    icon: "🏦",
    placeholder: "Account number",
    description: "Bank account number (encrypted at rest)",
    inputType: "text" as const,
    sensitive: true,
    color: {
      border: "border-green-500/50",
      bg: "bg-green-500/10",
      text: "text-green-500",
      glow: "shadow-[0_0_16px_rgba(34,197,94,0.2)]",
    },
  },
  "account-holder-name": {
    id: "account-holder-name",
    category: "financial" as const,
    label: "Account Holder",
    icon: "👤",
    placeholder: "John A. Smith",
    description: "Name on the bank or payment account",
    inputType: "text" as const,
    autoComplete: "name",
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-green-400/50",
      bg: "bg-green-400/10",
      text: "text-green-400",
      glow: "shadow-[0_0_16px_rgba(74,222,128,0.2)]",
    },
  },
  "routing-number": {
    id: "routing-number",
    category: "financial" as const,
    label: "Routing Number",
    icon: "🔗",
    placeholder: "XXXXXXXXX",
    description: "Bank routing/ABA number",
    inputType: "text" as const,
    sensitive: true,
    validation: { pattern: "^\\d{9}$" },
    color: {
      border: "border-green-500/50",
      bg: "bg-green-500/10",
      text: "text-green-500",
      glow: "shadow-[0_0_16px_rgba(34,197,94,0.2)]",
    },
  },
  "credit-card-number": {
    id: "credit-card-number",
    category: "financial" as const,
    label: "Card Number",
    icon: "💳",
    placeholder: "4242 4242 4242 4242",
    description: "Credit or debit card number with brand detection",
    inputType: "text" as const,
    autoComplete: "cc-number",
    sensitive: true,
    validation: { minLength: 13, maxLength: 23 },
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
  "cardholder-name": {
    id: "cardholder-name",
    category: "financial" as const,
    label: "Cardholder Name",
    icon: "👤",
    placeholder: "Name on card",
    description: "Name as printed on the payment card",
    inputType: "text" as const,
    autoComplete: "cc-name",
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "credit-card-expiry": {
    id: "credit-card-expiry",
    category: "financial" as const,
    label: "Card Expiration",
    icon: "📅",
    placeholder: "MM/YY",
    description: "Card expiration month and year",
    inputType: "text" as const,
    autoComplete: "cc-exp",
    validation: { minLength: 4, maxLength: 5 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "credit-card-cvc": {
    id: "credit-card-cvc",
    category: "financial" as const,
    label: "Card CVC",
    icon: "🔒",
    placeholder: "123",
    description: "Card security code / CVV",
    inputType: "text" as const,
    autoComplete: "cc-csc",
    sensitive: true,
    validation: { minLength: 3, maxLength: 4 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "billing-zip": {
    id: "billing-zip",
    category: "financial" as const,
    label: "Billing ZIP",
    icon: "📮",
    placeholder: "10001",
    description: "Billing postal code for card verification",
    inputType: "text" as const,
    autoComplete: "postal-code",
    validation: { pattern: "^[\\dA-Z -]{3,10}$" },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  iban: {
    id: "iban",
    category: "financial" as const,
    label: "IBAN",
    icon: "🏦",
    placeholder: "GB82 WEST 1234 5698 7654 32",
    description: "International Bank Account Number",
    inputType: "text" as const,
    sensitive: true,
    validation: { minLength: 15, maxLength: 34 },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "swift-bic": {
    id: "swift-bic",
    category: "financial" as const,
    label: "SWIFT / BIC",
    icon: "🌍",
    placeholder: "DEUTDEFF",
    description: "International bank SWIFT / BIC code",
    inputType: "text" as const,
    validation: { minLength: 8, maxLength: 11 },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "invoice-number": {
    id: "invoice-number",
    category: "financial" as const,
    label: "Invoice Number",
    icon: "🧾",
    placeholder: "INV-2026-001",
    description: "Invoice or accounts receivable reference",
    inputType: "text" as const,
    validation: { maxLength: 40 },
    color: {
      border: "border-green-300/50",
      bg: "bg-green-300/10",
      text: "text-green-300",
      glow: "shadow-[0_0_16px_rgba(134,239,172,0.16)]",
    },
  },
  "purchase-order": {
    id: "purchase-order",
    category: "financial" as const,
    label: "Purchase Order",
    icon: "📦",
    placeholder: "PO-88217",
    description: "Purchase order or procurement reference",
    inputType: "text" as const,
    validation: { maxLength: 40 },
    color: {
      border: "border-green-300/50",
      bg: "bg-green-300/10",
      text: "text-green-300",
      glow: "shadow-[0_0_16px_rgba(134,239,172,0.16)]",
    },
  },
  "payment-request": {
    id: "payment-request",
    category: "financial" as const,
    label: "Payment Request",
    icon: "💳",
    placeholder: "Collect payment at signing",
    description: "Trigger a BYO provider checkout flow before completion",
    inputType: "payment" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
};

// ─── Web3 Fields ─────────────────────────────────────────────────────────────

export const WEB3_FIELDS = {
  "wallet-address": {
    id: "wallet-address",
    category: "web3" as const,
    label: "Wallet Address",
    icon: "🔐",
    placeholder: "0x... / bc1... / So1...",
    description: "Crypto wallet address (ETH, BTC, or SOL)",
    inputType: "wallet" as const,
    autoFill: "wallet-address" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "eth-address": {
    id: "eth-address",
    category: "web3" as const,
    label: "Ethereum Address",
    icon: "⟠",
    placeholder: "0x...",
    description: "Ethereum wallet address (0x...)",
    inputType: "text" as const,
    validation: { pattern: "^0x[a-fA-F0-9]{40}$" },
    autoFill: "wallet-address" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "btc-address": {
    id: "btc-address",
    category: "web3" as const,
    label: "Bitcoin Address",
    icon: "₿",
    placeholder: "bc1... / 1... / 3...",
    description: "Bitcoin wallet address",
    inputType: "text" as const,
    color: {
      border: "border-orange-500/50",
      bg: "bg-orange-500/10",
      text: "text-orange-500",
      glow: "shadow-[0_0_16px_rgba(249,115,22,0.2)]",
    },
  },
  "sol-address": {
    id: "sol-address",
    category: "web3" as const,
    label: "Solana Address",
    icon: "◎",
    placeholder: "So1...",
    description: "Solana wallet address",
    inputType: "text" as const,
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "ens-name": {
    id: "ens-name",
    category: "web3" as const,
    label: "ENS Name",
    icon: "🔷",
    placeholder: "vitalik.eth",
    description: "Ethereum Name Service domain",
    inputType: "text" as const,
    validation: { pattern: "^[\\w-]+\\.eth$" },
    color: {
      border: "border-blue-500/50",
      bg: "bg-blue-500/10",
      text: "text-blue-500",
      glow: "shadow-[0_0_16px_rgba(59,130,246,0.2)]",
    },
  },
  "token-amount": {
    id: "token-amount",
    category: "web3" as const,
    label: "Token Amount",
    icon: "🪙",
    placeholder: "0.00",
    description: "Cryptocurrency or token amount",
    inputType: "number" as const,
    color: {
      border: "border-yellow-400/50",
      bg: "bg-yellow-400/10",
      text: "text-yellow-400",
      glow: "shadow-[0_0_16px_rgba(250,204,21,0.2)]",
    },
  },
  "tx-hash": {
    id: "tx-hash",
    category: "web3" as const,
    label: "Transaction Hash",
    icon: "#",
    placeholder: "0x...",
    description: "Blockchain transaction hash for reference",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "smart-contract": {
    id: "smart-contract",
    category: "web3" as const,
    label: "Contract Address",
    icon: "📜",
    placeholder: "0x...",
    description: "Smart contract address",
    inputType: "text" as const,
    validation: { pattern: "^0x[a-fA-F0-9]{40}$" },
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },
  "chain-name": {
    id: "chain-name",
    category: "web3" as const,
    label: "Blockchain",
    icon: "⛓",
    placeholder: "Ethereum",
    description: "Blockchain network name",
    inputType: "select" as const,
    validation: {
      options: [
        "Ethereum",
        "Bitcoin",
        "Solana",
        "Polygon",
        "Arbitrum",
        "Optimism",
        "Base",
        "Avalanche",
        "BSC",
        "Other",
      ],
    },
    autoFill: "chain-name" as const,
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "nft-id": {
    id: "nft-id",
    category: "web3" as const,
    label: "NFT / Token ID",
    icon: "🖼",
    placeholder: "#1234",
    description: "NFT token ID",
    inputType: "text" as const,
    color: {
      border: "border-rose-400/50",
      bg: "bg-rose-400/10",
      text: "text-rose-400",
      glow: "shadow-[0_0_16px_rgba(251,113,133,0.2)]",
    },
  },
  "dao-name": {
    id: "dao-name",
    category: "web3" as const,
    label: "DAO Name",
    icon: "🏛",
    placeholder: "MakerDAO",
    description: "Decentralized Autonomous Organization name",
    inputType: "text" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
};
