// Field definitions: Legal, Verification, Signature, Document
// Extracted from field-registry.ts to reduce file size

// ─── Legal / Date Fields ─────────────────────────────────────────────────────

export const LEGAL_FIELDS = {
  date: {
    id: "date",
    category: "legal" as const,
    label: "Date",
    icon: "📅",
    placeholder: "MM/DD/YYYY",
    description: "Date field",
    inputType: "date" as const,
    autoFill: "current-date" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "effective-date": {
    id: "effective-date",
    category: "legal" as const,
    label: "Effective Date",
    icon: "📅",
    placeholder: "MM/DD/YYYY",
    description: "Date the agreement becomes effective",
    inputType: "date" as const,
    autoFill: "current-date" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "expiration-date": {
    id: "expiration-date",
    category: "legal" as const,
    label: "Expiration Date",
    icon: "⏰",
    placeholder: "MM/DD/YYYY",
    description: "Date the agreement expires",
    inputType: "date" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "renewal-date": {
    id: "renewal-date",
    category: "legal" as const,
    label: "Renewal Date",
    icon: "🔁",
    placeholder: "MM/DD/YYYY",
    description: "Automatic renewal or extension date",
    inputType: "date" as const,
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "term-length": {
    id: "term-length",
    category: "legal" as const,
    label: "Term Length",
    icon: "📏",
    placeholder: "24 months",
    description: "Duration of the agreement",
    inputType: "text" as const,
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "notice-period": {
    id: "notice-period",
    category: "legal" as const,
    label: "Notice Period",
    icon: "⏳",
    placeholder: "30 days",
    description: "Required advance notice period",
    inputType: "text" as const,
    validation: { maxLength: 30 },
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "contract-id": {
    id: "contract-id",
    category: "legal" as const,
    label: "Contract ID",
    icon: "#",
    placeholder: "CTR-2026-0001",
    description: "Internal contract or agreement identifier",
    inputType: "text" as const,
    validation: { maxLength: 50 },
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  jurisdiction: {
    id: "jurisdiction",
    category: "legal" as const,
    label: "Governing Jurisdiction",
    icon: "⚖",
    placeholder: "State of Delaware, USA",
    description: "Legal jurisdiction that governs the agreement",
    inputType: "text" as const,
    color: {
      border: "border-amber-500/50",
      bg: "bg-amber-500/10",
      text: "text-amber-500",
      glow: "shadow-[0_0_16px_rgba(245,158,11,0.2)]",
    },
  },
  "governing-law": {
    id: "governing-law",
    category: "legal" as const,
    label: "Governing Law",
    icon: "📕",
    placeholder: "Laws of the State of...",
    description: "Which body of law governs the agreement",
    inputType: "text" as const,
    color: {
      border: "border-amber-500/50",
      bg: "bg-amber-500/10",
      text: "text-amber-500",
      glow: "shadow-[0_0_16px_rgba(245,158,11,0.2)]",
    },
  },
  "witness-name": {
    id: "witness-name",
    category: "legal" as const,
    label: "Witness Name",
    icon: "👁",
    placeholder: "Witness full name",
    description: "Name of witness to the signing",
    inputType: "text" as const,
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "notary-field": {
    id: "notary-field",
    category: "legal" as const,
    label: "Notary Public",
    icon: "🪪",
    placeholder: "Notary name and commission #",
    description: "Notary public details",
    inputType: "text" as const,
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "clause-number": {
    id: "clause-number",
    category: "legal" as const,
    label: "Clause Reference",
    icon: "§",
    placeholder: "Section 4.2(b)",
    description: "Reference to a specific clause or section",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
};

// ─── Verification Fields ─────────────────────────────────────────────────────

export const VERIFICATION_FIELDS = {
  "acknowledge-checkbox": {
    id: "acknowledge-checkbox",
    category: "verification" as const,
    label: "Acknowledgment",
    icon: "☑",
    placeholder: "I acknowledge and agree",
    description: "Checkbox requiring explicit acknowledgment",
    inputType: "checkbox" as const,
    color: {
      border: "border-yellow-400/50",
      bg: "bg-yellow-400/10",
      text: "text-yellow-400",
      glow: "shadow-[0_0_16px_rgba(250,204,21,0.2)]",
    },
  },
  "risk-warning": {
    id: "risk-warning",
    category: "verification" as const,
    label: "Risk Acknowledgment",
    icon: "⚠",
    placeholder: "I understand and accept the risks",
    description: "Explicit risk disclosure acceptance (required for web3)",
    inputType: "checkbox" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "age-verification": {
    id: "age-verification",
    category: "verification" as const,
    label: "Age Verification (18+)",
    icon: "🔞",
    placeholder: "I confirm I am 18 years or older",
    description: "Legal age verification checkbox",
    inputType: "checkbox" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "twitter-handle": {
    id: "twitter-handle",
    category: "verification" as const,
    label: "X (Twitter) Handle",
    icon: "𝕏",
    placeholder: "@username",
    description: "Twitter/X username for social verification",
    inputType: "text" as const,
    prefix: "@",
    validation: { pattern: "^@?[\\w]{1,15}$" },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "discord-handle": {
    id: "discord-handle",
    category: "verification" as const,
    label: "Discord Username",
    icon: "💬",
    placeholder: "username#0000",
    description: "Discord username for verification",
    inputType: "text" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "telegram-handle": {
    id: "telegram-handle",
    category: "verification" as const,
    label: "Telegram Username",
    icon: "✈",
    placeholder: "@username",
    description: "Telegram username",
    inputType: "text" as const,
    prefix: "@",
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "github-handle": {
    id: "github-handle",
    category: "verification" as const,
    label: "GitHub Username",
    icon: "🐙",
    placeholder: "username",
    description: "GitHub username for developer verification",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "id-verification": {
    id: "id-verification",
    category: "verification" as const,
    label: "ID Verification",
    icon: "🪪",
    placeholder: "Verify signer identity",
    description: "Run built-in algorithmic identity checks from signer-provided data",
    inputType: "idv" as const,
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },

  // ── OAuth-verified social fields (signer proves ownership via login) ──
  "x-verify": {
    id: "x-verify",
    category: "verification" as const,
    label: "Verify X (Twitter)",
    icon: "𝕏",
    placeholder: "Verify your X account",
    description: "Signer proves X/Twitter account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "github-verify": {
    id: "github-verify",
    category: "verification" as const,
    label: "Verify GitHub",
    icon: "🐙",
    placeholder: "Verify your GitHub account",
    description: "Signer proves GitHub account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "discord-verify": {
    id: "discord-verify",
    category: "verification" as const,
    label: "Verify Discord",
    icon: "💬",
    placeholder: "Verify your Discord account",
    description: "Signer proves Discord account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "google-verify": {
    id: "google-verify",
    category: "verification" as const,
    label: "Verify Google",
    icon: "🔵",
    placeholder: "Verify your Google account",
    description: "Signer proves Google account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
};

// ─── Signature Fields ────────────────────────────────────────────────────────

export const SIGNATURE_FIELDS = {
  signature: {
    id: "signature",
    category: "signature" as const,
    label: "Signature",
    icon: "✍",
    placeholder: "Draw your signature",
    description: "Hand-drawn or typed signature",
    inputType: "signature" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
  initials: {
    id: "initials",
    category: "signature" as const,
    label: "Initials",
    icon: "✏",
    placeholder: "J.S.",
    description: "Your initials (for clause acknowledgment)",
    inputType: "initials" as const,
    validation: { maxLength: 5 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.15)]",
    },
  },
};

// ─── Document / Structural Fields ────────────────────────────────────────────

export const DOCUMENT_FIELDS = {
  "free-text": {
    id: "free-text",
    category: "document" as const,
    label: "Free Text",
    icon: "📝",
    placeholder: "Enter text...",
    description: "Open text field for custom input",
    inputType: "textarea" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  url: {
    id: "url",
    category: "document" as const,
    label: "URL",
    icon: "🔗",
    placeholder: "https://example.com",
    description: "Generic URL or link field",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  dropdown: {
    id: "dropdown",
    category: "document" as const,
    label: "Dropdown Select",
    icon: "▾",
    placeholder: "Select an option",
    description: "Dropdown with predefined choices",
    inputType: "select" as const,
    validation: { options: ["Option A", "Option B", "Option C"] },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "radio-group": {
    id: "radio-group",
    category: "document" as const,
    label: "Radio Choices",
    icon: "◉",
    placeholder: "Choose one",
    description: "Single-choice radio options",
    inputType: "radio" as const,
    validation: { options: ["Yes", "No"] },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  number: {
    id: "number",
    category: "document" as const,
    label: "Number",
    icon: "#",
    placeholder: "0",
    description: "Numeric value",
    inputType: "number" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  time: {
    id: "time",
    category: "document" as const,
    label: "Time",
    icon: "🕒",
    placeholder: "09:30",
    description: "Time of day",
    inputType: "time" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  datetime: {
    id: "datetime",
    category: "document" as const,
    label: "Date & Time",
    icon: "🗓",
    placeholder: "MM/DD/YYYY 09:30",
    description: "Combined date and time value",
    inputType: "datetime-local" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  "file-attachment": {
    id: "file-attachment",
    category: "document" as const,
    label: "File Attachment",
    icon: "📎",
    placeholder: "Upload a file",
    description: "Attach a supporting document or image",
    inputType: "file" as const,
    color: {
      border: "border-zinc-400/50",
      bg: "bg-zinc-400/10",
      text: "text-zinc-400",
      glow: "shadow-[0_0_16px_rgba(161,161,170,0.15)]",
    },
  },
  "custom-field": {
    id: "custom-field",
    category: "document" as const,
    label: "Custom Field",
    icon: "✨",
    placeholder: "Configure custom input",
    description: "Build your own field with custom input type, validation, logic, badge, and visuals",
    inputType: "text" as const,
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },
};
