// Field definitions: Identity, Contact, Address
// Extracted from field-registry.ts to reduce file size

// ─── Identity Fields ─────────────────────────────────────────────────────────

export const IDENTITY_FIELDS = {
  "full-name": {
    id: "full-name",
    category: "identity" as const,
    label: "Full Legal Name",
    icon: "👤",
    placeholder: "John A. Smith",
    description: "Full legal name as it appears on government ID",
    inputType: "text" as const,
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "first-name": {
    id: "first-name",
    category: "identity" as const,
    label: "First Name",
    icon: "👤",
    placeholder: "John",
    description: "Legal first name",
    inputType: "text" as const,
    autoComplete: "given-name",
    validation: { minLength: 1, maxLength: 50 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "middle-name": {
    id: "middle-name",
    category: "identity" as const,
    label: "Middle Name",
    icon: "👤",
    placeholder: "Alexander",
    description: "Middle or additional legal name",
    inputType: "text" as const,
    autoComplete: "additional-name",
    validation: { maxLength: 50 },
    color: {
      border: "border-blue-300/50",
      bg: "bg-blue-300/10",
      text: "text-blue-300",
      glow: "shadow-[0_0_16px_rgba(147,197,253,0.18)]",
    },
  },
  "last-name": {
    id: "last-name",
    category: "identity" as const,
    label: "Last Name",
    icon: "👤",
    placeholder: "Smith",
    description: "Legal last/family name",
    inputType: "text" as const,
    autoComplete: "family-name",
    validation: { minLength: 1, maxLength: 50 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "preferred-name": {
    id: "preferred-name",
    category: "identity" as const,
    label: "Preferred Name",
    icon: "✨",
    placeholder: "Johnny",
    description: "Nickname or preferred name",
    inputType: "text" as const,
    autoComplete: "nickname",
    validation: { maxLength: 50 },
    color: {
      border: "border-sky-300/50",
      bg: "bg-sky-300/10",
      text: "text-sky-300",
      glow: "shadow-[0_0_16px_rgba(125,211,252,0.18)]",
    },
  },
  "company-name": {
    id: "company-name",
    category: "identity" as const,
    label: "Company / Organization",
    icon: "🏢",
    placeholder: "Acme Corp",
    description: "Legal entity or business name",
    inputType: "text" as const,
    autoComplete: "organization",
    validation: { maxLength: 200 },
    color: {
      border: "border-amber-400/50",
      bg: "bg-amber-400/10",
      text: "text-amber-400",
      glow: "shadow-[0_0_16px_rgba(251,191,36,0.2)]",
    },
  },
  "job-title": {
    id: "job-title",
    category: "identity" as const,
    label: "Title / Role",
    icon: "🏷",
    placeholder: "Chief Executive Officer",
    description: "Job title or role within organization",
    inputType: "text" as const,
    autoComplete: "organization-title",
    validation: { maxLength: 100 },
    color: {
      border: "border-pink-400/50",
      bg: "bg-pink-400/10",
      text: "text-pink-400",
      glow: "shadow-[0_0_16px_rgba(244,114,182,0.2)]",
    },
  },
  "tax-id": {
    id: "tax-id",
    category: "identity" as const,
    label: "Tax ID / EIN",
    icon: "🔢",
    placeholder: "XX-XXXXXXX",
    description: "Federal tax identification number",
    inputType: "text" as const,
    validation: { pattern: "^\\d{2}-?\\d{7}$" },
    mask: "##-#######",
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  ssn: {
    id: "ssn",
    category: "identity" as const,
    label: "SSN (last 4)",
    icon: "🔒",
    placeholder: "••••",
    description: "Last 4 digits of Social Security Number",
    inputType: "text" as const,
    validation: { pattern: "^\\d{4}$", maxLength: 4 },
    sensitive: true,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "ssn-full": {
    id: "ssn-full",
    category: "identity" as const,
    label: "SSN (full)",
    icon: "🔒",
    placeholder: "•••-••-••••",
    description: "Full Social Security Number (encrypted, masked by default)",
    inputType: "text" as const,
    validation: { pattern: "^\\d{3}-?\\d{2}-?\\d{4}$", maxLength: 11 },
    mask: "###-##-####",
    sensitive: true,
    color: {
      border: "border-red-500/50",
      bg: "bg-red-500/10",
      text: "text-red-500",
      glow: "shadow-[0_0_16px_rgba(239,68,68,0.2)]",
    },
  },
  dob: {
    id: "dob",
    category: "identity" as const,
    label: "Date of Birth",
    icon: "🎂",
    placeholder: "MM/DD/YYYY",
    description: "Date of birth for identity verification",
    inputType: "date" as const,
    autoComplete: "bday",
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "passport-number": {
    id: "passport-number",
    category: "identity" as const,
    label: "Passport Number",
    icon: "🛂",
    placeholder: "123456789",
    description: "Government-issued passport number",
    inputType: "text" as const,
    validation: { minLength: 6, maxLength: 12 },
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(217,70,239,0.18)]",
    },
  },
  "drivers-license": {
    id: "drivers-license",
    category: "identity" as const,
    label: "Driver License",
    icon: "🪪",
    placeholder: "D123-456-7890",
    description: "Driver license or state-issued ID number",
    inputType: "text" as const,
    validation: { minLength: 5, maxLength: 20 },
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "national-id": {
    id: "national-id",
    category: "identity" as const,
    label: "National ID",
    icon: "🧾",
    placeholder: "National identification number",
    description: "National or civil identification number",
    inputType: "text" as const,
    validation: { minLength: 6, maxLength: 20 },
    color: {
      border: "border-zinc-400/50",
      bg: "bg-zinc-400/10",
      text: "text-zinc-400",
      glow: "shadow-[0_0_16px_rgba(161,161,170,0.16)]",
    },
  },
  nationality: {
    id: "nationality",
    category: "identity" as const,
    label: "Nationality",
    icon: "🌐",
    placeholder: "United States",
    description: "Citizenship or nationality",
    inputType: "text" as const,
    autoComplete: "country-name",
    validation: { maxLength: 80 },
    color: {
      border: "border-cyan-300/50",
      bg: "bg-cyan-300/10",
      text: "text-cyan-300",
      glow: "shadow-[0_0_16px_rgba(103,232,249,0.16)]",
    },
  },
};

// ─── Contact Fields ──────────────────────────────────────────────────────────

export const CONTACT_FIELDS = {
  email: {
    id: "email",
    category: "contact" as const,
    label: "Email Address",
    icon: "✉",
    placeholder: "you@example.com",
    description: "Primary contact email",
    inputType: "email" as const,
    autoComplete: "email",
    validation: { pattern: "^[^@]+@[^@]+\\.[^@]+$" },
    color: {
      border: "border-cyan-400/50",
      bg: "bg-cyan-400/10",
      text: "text-cyan-400",
      glow: "shadow-[0_0_16px_rgba(34,211,238,0.2)]",
    },
  },
  "secondary-email": {
    id: "secondary-email",
    category: "contact" as const,
    label: "Secondary Email",
    icon: "✉",
    placeholder: "backup@example.com",
    description: "Backup or alternate contact email",
    inputType: "email" as const,
    autoComplete: "email",
    validation: { pattern: "^[^@]+@[^@]+\\.[^@]+$" },
    color: {
      border: "border-cyan-300/50",
      bg: "bg-cyan-300/10",
      text: "text-cyan-300",
      glow: "shadow-[0_0_16px_rgba(103,232,249,0.16)]",
    },
  },
  phone: {
    id: "phone",
    category: "contact" as const,
    label: "Phone Number",
    icon: "📞",
    placeholder: "+1 (555) 000-0000",
    description: "Contact phone with country code",
    inputType: "tel" as const,
    autoComplete: "tel",
    validation: { pattern: "^\\+?[\\d\\s()-]{7,20}$" },
    color: {
      border: "border-teal-400/50",
      bg: "bg-teal-400/10",
      text: "text-teal-400",
      glow: "shadow-[0_0_16px_rgba(45,212,191,0.2)]",
    },
  },
  "fax-number": {
    id: "fax-number",
    category: "contact" as const,
    label: "Fax Number",
    icon: "📠",
    placeholder: "+1 (555) 222-3333",
    description: "Fax number for formal notices",
    inputType: "tel" as const,
    autoComplete: "tel-national",
    validation: { pattern: "^\\+?[\\d\\s()-]{7,20}$" },
    color: {
      border: "border-teal-300/50",
      bg: "bg-teal-300/10",
      text: "text-teal-300",
      glow: "shadow-[0_0_16px_rgba(94,234,212,0.16)]",
    },
  },
  website: {
    id: "website",
    category: "contact" as const,
    label: "Website",
    icon: "🌐",
    placeholder: "https://example.com",
    description: "Website or company URL",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "linkedin-url": {
    id: "linkedin-url",
    category: "contact" as const,
    label: "LinkedIn URL",
    icon: "🔗",
    placeholder: "https://linkedin.com/in/username",
    description: "LinkedIn profile or company page URL",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-blue-500/50",
      bg: "bg-blue-500/10",
      text: "text-blue-500",
      glow: "shadow-[0_0_16px_rgba(59,130,246,0.2)]",
    },
  },
};

// ─── Address Fields ──────────────────────────────────────────────────────────

export const ADDRESS_FIELDS = {
  "street-address": {
    id: "street-address",
    category: "address" as const,
    label: "Street Address",
    icon: "🏠",
    placeholder: "123 Main Street, Suite 100",
    description: "Full street address including unit/suite",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  "address-line-2": {
    id: "address-line-2",
    category: "address" as const,
    label: "Address Line 2",
    icon: "🏢",
    placeholder: "Apartment, suite, building",
    description: "Apartment, suite, floor, or unit",
    inputType: "text" as const,
    autoComplete: "address-line2",
    validation: { maxLength: 120 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  "billing-address": {
    id: "billing-address",
    category: "address" as const,
    label: "Billing Address",
    icon: "💳",
    placeholder: "123 Billing Street",
    description: "Billing address for invoices or payments",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "mailing-address": {
    id: "mailing-address",
    category: "address" as const,
    label: "Mailing Address",
    icon: "📮",
    placeholder: "123 Mailing Street",
    description: "Postal mailing address",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  "full-address": {
    id: "full-address",
    category: "address" as const,
    label: "Full Mailing Address",
    icon: "📬",
    placeholder: "123 Main St, City, ST 12345, US",
    description: "Complete mailing address with city, state, zip, country",
    inputType: "textarea" as const,
    autoComplete: "street-address",
    validation: { maxLength: 500 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  city: {
    id: "city",
    category: "address" as const,
    label: "City",
    icon: "🏙",
    placeholder: "New York",
    description: "City or municipality",
    inputType: "text" as const,
    autoComplete: "address-level2",
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  county: {
    id: "county",
    category: "address" as const,
    label: "County",
    icon: "🗺",
    placeholder: "Los Angeles County",
    description: "County or administrative district",
    inputType: "text" as const,
    validation: { maxLength: 80 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  state: {
    id: "state",
    category: "address" as const,
    label: "State / Province",
    icon: "📍",
    placeholder: "NY",
    description: "State, province, or region",
    inputType: "text" as const,
    autoComplete: "address-level1",
    validation: { maxLength: 50 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  zip: {
    id: "zip",
    category: "address" as const,
    label: "ZIP / Postal Code",
    icon: "📮",
    placeholder: "10001",
    description: "ZIP or postal code",
    inputType: "text" as const,
    autoComplete: "postal-code",
    validation: { pattern: "^[\\dA-Z -]{3,10}$" },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  country: {
    id: "country",
    category: "address" as const,
    label: "Country",
    icon: "🌍",
    placeholder: "United States",
    description: "Country of residence or incorporation",
    inputType: "text" as const,
    autoComplete: "country-name",
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
};
