// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPREHENSIVE FIELD REGISTRY
// Every field type a contract could need — standard, web3, verification, legal
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export type FieldCategory =
  | "identity"
  | "contact"
  | "address"
  | "financial"
  | "web3"
  | "legal"
  | "verification"
  | "signature"
  | "document";

export type FieldTypeId = keyof typeof FIELD_REGISTRY;

export type FieldConfig = {
  id: string;
  category: FieldCategory;
  label: string;
  icon: string;
  placeholder: string;
  description: string;
  inputType:
    | "text"
    | "email"
    | "tel"
    | "date"
    | "number"
    | "textarea"
    | "select"
    | "checkbox"
    | "signature"
    | "initials"
    | "address-group"
    | "wallet"
    | "file"
    | "payment"
    | "idv"
    | "social-verify"
    | "url"
    | "time"
    | "datetime-local"
    | "radio";
  validation?: {
    pattern?: string;
    minLength?: number;
    maxLength?: number;
    options?: string[];
  };
  color: {
    border: string;
    bg: string;
    text: string;
    glow: string;
  };
  autoFill?: "wallet-address" | "current-date" | "current-email" | "chain-name";
  autoComplete?: string;
  mask?: string;
  prefix?: string;
  sensitive?: boolean;
};

// ─── Identity Fields ─────────────────────────────────────────────────────────

const IDENTITY_FIELDS = {
  "full-name": {
    id: "full-name",
    category: "identity" as const,
    label: "Full Legal Name",
    icon: "👤",
    placeholder: "John A. Smith",
    description: "Full legal name as it appears on government ID",
    inputType: "text" as const,
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "first-name": {
    id: "first-name",
    category: "identity" as const,
    label: "First Name",
    icon: "👤",
    placeholder: "John",
    description: "Legal first name",
    inputType: "text" as const,
    autoComplete: "given-name",
    validation: { minLength: 1, maxLength: 50 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "middle-name": {
    id: "middle-name",
    category: "identity" as const,
    label: "Middle Name",
    icon: "👤",
    placeholder: "Alexander",
    description: "Middle or additional legal name",
    inputType: "text" as const,
    autoComplete: "additional-name",
    validation: { maxLength: 50 },
    color: {
      border: "border-blue-300/50",
      bg: "bg-blue-300/10",
      text: "text-blue-300",
      glow: "shadow-[0_0_16px_rgba(147,197,253,0.18)]",
    },
  },
  "last-name": {
    id: "last-name",
    category: "identity" as const,
    label: "Last Name",
    icon: "👤",
    placeholder: "Smith",
    description: "Legal last/family name",
    inputType: "text" as const,
    autoComplete: "family-name",
    validation: { minLength: 1, maxLength: 50 },
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "preferred-name": {
    id: "preferred-name",
    category: "identity" as const,
    label: "Preferred Name",
    icon: "✨",
    placeholder: "Johnny",
    description: "Nickname or preferred name",
    inputType: "text" as const,
    autoComplete: "nickname",
    validation: { maxLength: 50 },
    color: {
      border: "border-sky-300/50",
      bg: "bg-sky-300/10",
      text: "text-sky-300",
      glow: "shadow-[0_0_16px_rgba(125,211,252,0.18)]",
    },
  },
  "company-name": {
    id: "company-name",
    category: "identity" as const,
    label: "Company / Organization",
    icon: "🏢",
    placeholder: "Acme Corp",
    description: "Legal entity or business name",
    inputType: "text" as const,
    autoComplete: "organization",
    validation: { maxLength: 200 },
    color: {
      border: "border-amber-400/50",
      bg: "bg-amber-400/10",
      text: "text-amber-400",
      glow: "shadow-[0_0_16px_rgba(251,191,36,0.2)]",
    },
  },
  "job-title": {
    id: "job-title",
    category: "identity" as const,
    label: "Title / Role",
    icon: "🏷",
    placeholder: "Chief Executive Officer",
    description: "Job title or role within organization",
    inputType: "text" as const,
    autoComplete: "organization-title",
    validation: { maxLength: 100 },
    color: {
      border: "border-pink-400/50",
      bg: "bg-pink-400/10",
      text: "text-pink-400",
      glow: "shadow-[0_0_16px_rgba(244,114,182,0.2)]",
    },
  },
  "tax-id": {
    id: "tax-id",
    category: "identity" as const,
    label: "Tax ID / EIN",
    icon: "🔢",
    placeholder: "XX-XXXXXXX",
    description: "Federal tax identification number",
    inputType: "text" as const,
    validation: { pattern: "^\\d{2}-?\\d{7}$" },
    mask: "##-#######",
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  ssn: {
    id: "ssn",
    category: "identity" as const,
    label: "SSN (last 4)",
    icon: "🔒",
    placeholder: "••••",
    description: "Last 4 digits of Social Security Number",
    inputType: "text" as const,
    validation: { pattern: "^\\d{4}$", maxLength: 4 },
    sensitive: true,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "ssn-full": {
    id: "ssn-full",
    category: "identity" as const,
    label: "SSN (full)",
    icon: "🔒",
    placeholder: "•••-••-••••",
    description: "Full Social Security Number (encrypted, masked by default)",
    inputType: "text" as const,
    validation: { pattern: "^\\d{3}-?\\d{2}-?\\d{4}$", maxLength: 11 },
    mask: "###-##-####",
    sensitive: true,
    color: {
      border: "border-red-500/50",
      bg: "bg-red-500/10",
      text: "text-red-500",
      glow: "shadow-[0_0_16px_rgba(239,68,68,0.2)]",
    },
  },
  dob: {
    id: "dob",
    category: "identity" as const,
    label: "Date of Birth",
    icon: "🎂",
    placeholder: "MM/DD/YYYY",
    description: "Date of birth for identity verification",
    inputType: "date" as const,
    autoComplete: "bday",
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "passport-number": {
    id: "passport-number",
    category: "identity" as const,
    label: "Passport Number",
    icon: "🛂",
    placeholder: "123456789",
    description: "Government-issued passport number",
    inputType: "text" as const,
    validation: { minLength: 6, maxLength: 12 },
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(217,70,239,0.18)]",
    },
  },
  "drivers-license": {
    id: "drivers-license",
    category: "identity" as const,
    label: "Driver License",
    icon: "🪪",
    placeholder: "D123-456-7890",
    description: "Driver license or state-issued ID number",
    inputType: "text" as const,
    validation: { minLength: 5, maxLength: 20 },
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "national-id": {
    id: "national-id",
    category: "identity" as const,
    label: "National ID",
    icon: "🧾",
    placeholder: "National identification number",
    description: "National or civil identification number",
    inputType: "text" as const,
    validation: { minLength: 6, maxLength: 20 },
    color: {
      border: "border-zinc-400/50",
      bg: "bg-zinc-400/10",
      text: "text-zinc-400",
      glow: "shadow-[0_0_16px_rgba(161,161,170,0.16)]",
    },
  },
  nationality: {
    id: "nationality",
    category: "identity" as const,
    label: "Nationality",
    icon: "🌐",
    placeholder: "United States",
    description: "Citizenship or nationality",
    inputType: "text" as const,
    autoComplete: "country-name",
    validation: { maxLength: 80 },
    color: {
      border: "border-cyan-300/50",
      bg: "bg-cyan-300/10",
      text: "text-cyan-300",
      glow: "shadow-[0_0_16px_rgba(103,232,249,0.16)]",
    },
  },
};

// ─── Contact Fields ──────────────────────────────────────────────────────────

const CONTACT_FIELDS = {
  email: {
    id: "email",
    category: "contact" as const,
    label: "Email Address",
    icon: "✉",
    placeholder: "you@example.com",
    description: "Primary contact email",
    inputType: "email" as const,
    autoComplete: "email",
    validation: { pattern: "^[^@]+@[^@]+\\.[^@]+$" },
    color: {
      border: "border-cyan-400/50",
      bg: "bg-cyan-400/10",
      text: "text-cyan-400",
      glow: "shadow-[0_0_16px_rgba(34,211,238,0.2)]",
    },
  },
  "secondary-email": {
    id: "secondary-email",
    category: "contact" as const,
    label: "Secondary Email",
    icon: "✉",
    placeholder: "backup@example.com",
    description: "Backup or alternate contact email",
    inputType: "email" as const,
    autoComplete: "email",
    validation: { pattern: "^[^@]+@[^@]+\\.[^@]+$" },
    color: {
      border: "border-cyan-300/50",
      bg: "bg-cyan-300/10",
      text: "text-cyan-300",
      glow: "shadow-[0_0_16px_rgba(103,232,249,0.16)]",
    },
  },
  phone: {
    id: "phone",
    category: "contact" as const,
    label: "Phone Number",
    icon: "📞",
    placeholder: "+1 (555) 000-0000",
    description: "Contact phone with country code",
    inputType: "tel" as const,
    autoComplete: "tel",
    validation: { pattern: "^\\+?[\\d\\s()-]{7,20}$" },
    color: {
      border: "border-teal-400/50",
      bg: "bg-teal-400/10",
      text: "text-teal-400",
      glow: "shadow-[0_0_16px_rgba(45,212,191,0.2)]",
    },
  },
  "fax-number": {
    id: "fax-number",
    category: "contact" as const,
    label: "Fax Number",
    icon: "📠",
    placeholder: "+1 (555) 222-3333",
    description: "Fax number for formal notices",
    inputType: "tel" as const,
    autoComplete: "tel-national",
    validation: { pattern: "^\\+?[\\d\\s()-]{7,20}$" },
    color: {
      border: "border-teal-300/50",
      bg: "bg-teal-300/10",
      text: "text-teal-300",
      glow: "shadow-[0_0_16px_rgba(94,234,212,0.16)]",
    },
  },
  website: {
    id: "website",
    category: "contact" as const,
    label: "Website",
    icon: "🌐",
    placeholder: "https://example.com",
    description: "Website or company URL",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "linkedin-url": {
    id: "linkedin-url",
    category: "contact" as const,
    label: "LinkedIn URL",
    icon: "🔗",
    placeholder: "https://linkedin.com/in/username",
    description: "LinkedIn profile or company page URL",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-blue-500/50",
      bg: "bg-blue-500/10",
      text: "text-blue-500",
      glow: "shadow-[0_0_16px_rgba(59,130,246,0.2)]",
    },
  },
};

// ─── Address Fields ──────────────────────────────────────────────────────────

const ADDRESS_FIELDS = {
  "street-address": {
    id: "street-address",
    category: "address" as const,
    label: "Street Address",
    icon: "🏠",
    placeholder: "123 Main Street, Suite 100",
    description: "Full street address including unit/suite",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  "address-line-2": {
    id: "address-line-2",
    category: "address" as const,
    label: "Address Line 2",
    icon: "🏢",
    placeholder: "Apartment, suite, building",
    description: "Apartment, suite, floor, or unit",
    inputType: "text" as const,
    autoComplete: "address-line2",
    validation: { maxLength: 120 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  "billing-address": {
    id: "billing-address",
    category: "address" as const,
    label: "Billing Address",
    icon: "💳",
    placeholder: "123 Billing Street",
    description: "Billing address for invoices or payments",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "mailing-address": {
    id: "mailing-address",
    category: "address" as const,
    label: "Mailing Address",
    icon: "📮",
    placeholder: "123 Mailing Street",
    description: "Postal mailing address",
    inputType: "text" as const,
    autoComplete: "street-address",
    validation: { maxLength: 200 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  "full-address": {
    id: "full-address",
    category: "address" as const,
    label: "Full Mailing Address",
    icon: "📬",
    placeholder: "123 Main St, City, ST 12345, US",
    description: "Complete mailing address with city, state, zip, country",
    inputType: "textarea" as const,
    autoComplete: "street-address",
    validation: { maxLength: 500 },
    color: {
      border: "border-purple-400/50",
      bg: "bg-purple-400/10",
      text: "text-purple-400",
      glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    },
  },
  city: {
    id: "city",
    category: "address" as const,
    label: "City",
    icon: "🏙",
    placeholder: "New York",
    description: "City or municipality",
    inputType: "text" as const,
    autoComplete: "address-level2",
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  county: {
    id: "county",
    category: "address" as const,
    label: "County",
    icon: "🗺",
    placeholder: "Los Angeles County",
    description: "County or administrative district",
    inputType: "text" as const,
    validation: { maxLength: 80 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  state: {
    id: "state",
    category: "address" as const,
    label: "State / Province",
    icon: "📍",
    placeholder: "NY",
    description: "State, province, or region",
    inputType: "text" as const,
    autoComplete: "address-level1",
    validation: { maxLength: 50 },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  zip: {
    id: "zip",
    category: "address" as const,
    label: "ZIP / Postal Code",
    icon: "📮",
    placeholder: "10001",
    description: "ZIP or postal code",
    inputType: "text" as const,
    autoComplete: "postal-code",
    validation: { pattern: "^[\\dA-Z -]{3,10}$" },
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
  country: {
    id: "country",
    category: "address" as const,
    label: "Country",
    icon: "🌍",
    placeholder: "United States",
    description: "Country of residence or incorporation",
    inputType: "text" as const,
    autoComplete: "country-name",
    color: {
      border: "border-purple-300/50",
      bg: "bg-purple-300/10",
      text: "text-purple-300",
      glow: "shadow-[0_0_16px_rgba(216,180,254,0.15)]",
    },
  },
};

// ─── Financial Fields ────────────────────────────────────────────────────────

const FINANCIAL_FIELDS = {
  "currency-amount": {
    id: "currency-amount",
    category: "financial" as const,
    label: "Amount (USD)",
    icon: "💲",
    placeholder: "0.00",
    description: "Dollar amount",
    inputType: "number" as const,
    prefix: "$",
    validation: { pattern: "^\\d+\\.?\\d{0,2}$" },
    color: {
      border: "border-green-400/50",
      bg: "bg-green-400/10",
      text: "text-green-400",
      glow: "shadow-[0_0_16px_rgba(74,222,128,0.2)]",
    },
  },
  percentage: {
    id: "percentage",
    category: "financial" as const,
    label: "Percentage",
    icon: "%",
    placeholder: "0.00",
    description: "Percentage value",
    inputType: "number" as const,
    validation: { pattern: "^\\d+\\.?\\d{0,4}$" },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "bank-account": {
    id: "bank-account",
    category: "financial" as const,
    label: "Bank Account",
    icon: "🏦",
    placeholder: "Account number",
    description: "Bank account number (encrypted at rest)",
    inputType: "text" as const,
    sensitive: true,
    color: {
      border: "border-green-500/50",
      bg: "bg-green-500/10",
      text: "text-green-500",
      glow: "shadow-[0_0_16px_rgba(34,197,94,0.2)]",
    },
  },
  "account-holder-name": {
    id: "account-holder-name",
    category: "financial" as const,
    label: "Account Holder",
    icon: "👤",
    placeholder: "John A. Smith",
    description: "Name on the bank or payment account",
    inputType: "text" as const,
    autoComplete: "name",
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-green-400/50",
      bg: "bg-green-400/10",
      text: "text-green-400",
      glow: "shadow-[0_0_16px_rgba(74,222,128,0.2)]",
    },
  },
  "routing-number": {
    id: "routing-number",
    category: "financial" as const,
    label: "Routing Number",
    icon: "🔗",
    placeholder: "XXXXXXXXX",
    description: "Bank routing/ABA number",
    inputType: "text" as const,
    sensitive: true,
    validation: { pattern: "^\\d{9}$" },
    color: {
      border: "border-green-500/50",
      bg: "bg-green-500/10",
      text: "text-green-500",
      glow: "shadow-[0_0_16px_rgba(34,197,94,0.2)]",
    },
  },
  "credit-card-number": {
    id: "credit-card-number",
    category: "financial" as const,
    label: "Card Number",
    icon: "💳",
    placeholder: "4242 4242 4242 4242",
    description: "Credit or debit card number with brand detection",
    inputType: "text" as const,
    autoComplete: "cc-number",
    sensitive: true,
    validation: { minLength: 13, maxLength: 23 },
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
  "cardholder-name": {
    id: "cardholder-name",
    category: "financial" as const,
    label: "Cardholder Name",
    icon: "👤",
    placeholder: "Name on card",
    description: "Name as printed on the payment card",
    inputType: "text" as const,
    autoComplete: "cc-name",
    validation: { minLength: 2, maxLength: 100 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "credit-card-expiry": {
    id: "credit-card-expiry",
    category: "financial" as const,
    label: "Card Expiration",
    icon: "📅",
    placeholder: "MM/YY",
    description: "Card expiration month and year",
    inputType: "text" as const,
    autoComplete: "cc-exp",
    validation: { minLength: 4, maxLength: 5 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "credit-card-cvc": {
    id: "credit-card-cvc",
    category: "financial" as const,
    label: "Card CVC",
    icon: "🔒",
    placeholder: "123",
    description: "Card security code / CVV",
    inputType: "text" as const,
    autoComplete: "cc-csc",
    sensitive: true,
    validation: { minLength: 3, maxLength: 4 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  "billing-zip": {
    id: "billing-zip",
    category: "financial" as const,
    label: "Billing ZIP",
    icon: "📮",
    placeholder: "10001",
    description: "Billing postal code for card verification",
    inputType: "text" as const,
    autoComplete: "postal-code",
    validation: { pattern: "^[\\dA-Z -]{3,10}$" },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.18)]",
    },
  },
  iban: {
    id: "iban",
    category: "financial" as const,
    label: "IBAN",
    icon: "🏦",
    placeholder: "GB82 WEST 1234 5698 7654 32",
    description: "International Bank Account Number",
    inputType: "text" as const,
    sensitive: true,
    validation: { minLength: 15, maxLength: 34 },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "swift-bic": {
    id: "swift-bic",
    category: "financial" as const,
    label: "SWIFT / BIC",
    icon: "🌍",
    placeholder: "DEUTDEFF",
    description: "International bank SWIFT / BIC code",
    inputType: "text" as const,
    validation: { minLength: 8, maxLength: 11 },
    color: {
      border: "border-lime-400/50",
      bg: "bg-lime-400/10",
      text: "text-lime-400",
      glow: "shadow-[0_0_16px_rgba(163,230,53,0.2)]",
    },
  },
  "invoice-number": {
    id: "invoice-number",
    category: "financial" as const,
    label: "Invoice Number",
    icon: "🧾",
    placeholder: "INV-2026-001",
    description: "Invoice or accounts receivable reference",
    inputType: "text" as const,
    validation: { maxLength: 40 },
    color: {
      border: "border-green-300/50",
      bg: "bg-green-300/10",
      text: "text-green-300",
      glow: "shadow-[0_0_16px_rgba(134,239,172,0.16)]",
    },
  },
  "purchase-order": {
    id: "purchase-order",
    category: "financial" as const,
    label: "Purchase Order",
    icon: "📦",
    placeholder: "PO-88217",
    description: "Purchase order or procurement reference",
    inputType: "text" as const,
    validation: { maxLength: 40 },
    color: {
      border: "border-green-300/50",
      bg: "bg-green-300/10",
      text: "text-green-300",
      glow: "shadow-[0_0_16px_rgba(134,239,172,0.16)]",
    },
  },
  "payment-request": {
    id: "payment-request",
    category: "financial" as const,
    label: "Payment Request",
    icon: "💳",
    placeholder: "Collect payment at signing",
    description: "Trigger a BYO provider checkout flow before completion",
    inputType: "payment" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
};

// ─── Web3 Fields ─────────────────────────────────────────────────────────────

const WEB3_FIELDS = {
  "wallet-address": {
    id: "wallet-address",
    category: "web3" as const,
    label: "Wallet Address",
    icon: "🔐",
    placeholder: "0x... / bc1... / So1...",
    description: "Crypto wallet address (ETH, BTC, or SOL)",
    inputType: "wallet" as const,
    autoFill: "wallet-address" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "eth-address": {
    id: "eth-address",
    category: "web3" as const,
    label: "Ethereum Address",
    icon: "⟠",
    placeholder: "0x...",
    description: "Ethereum wallet address (0x...)",
    inputType: "text" as const,
    validation: { pattern: "^0x[a-fA-F0-9]{40}$" },
    autoFill: "wallet-address" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "btc-address": {
    id: "btc-address",
    category: "web3" as const,
    label: "Bitcoin Address",
    icon: "₿",
    placeholder: "bc1... / 1... / 3...",
    description: "Bitcoin wallet address",
    inputType: "text" as const,
    color: {
      border: "border-orange-500/50",
      bg: "bg-orange-500/10",
      text: "text-orange-500",
      glow: "shadow-[0_0_16px_rgba(249,115,22,0.2)]",
    },
  },
  "sol-address": {
    id: "sol-address",
    category: "web3" as const,
    label: "Solana Address",
    icon: "◎",
    placeholder: "So1...",
    description: "Solana wallet address",
    inputType: "text" as const,
    color: {
      border: "border-violet-400/50",
      bg: "bg-violet-400/10",
      text: "text-violet-400",
      glow: "shadow-[0_0_16px_rgba(167,139,250,0.2)]",
    },
  },
  "ens-name": {
    id: "ens-name",
    category: "web3" as const,
    label: "ENS Name",
    icon: "🔷",
    placeholder: "vitalik.eth",
    description: "Ethereum Name Service domain",
    inputType: "text" as const,
    validation: { pattern: "^[\\w-]+\\.eth$" },
    color: {
      border: "border-blue-500/50",
      bg: "bg-blue-500/10",
      text: "text-blue-500",
      glow: "shadow-[0_0_16px_rgba(59,130,246,0.2)]",
    },
  },
  "token-amount": {
    id: "token-amount",
    category: "web3" as const,
    label: "Token Amount",
    icon: "🪙",
    placeholder: "0.00",
    description: "Cryptocurrency or token amount",
    inputType: "number" as const,
    color: {
      border: "border-yellow-400/50",
      bg: "bg-yellow-400/10",
      text: "text-yellow-400",
      glow: "shadow-[0_0_16px_rgba(250,204,21,0.2)]",
    },
  },
  "tx-hash": {
    id: "tx-hash",
    category: "web3" as const,
    label: "Transaction Hash",
    icon: "#",
    placeholder: "0x...",
    description: "Blockchain transaction hash for reference",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "smart-contract": {
    id: "smart-contract",
    category: "web3" as const,
    label: "Contract Address",
    icon: "📜",
    placeholder: "0x...",
    description: "Smart contract address",
    inputType: "text" as const,
    validation: { pattern: "^0x[a-fA-F0-9]{40}$" },
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },
  "chain-name": {
    id: "chain-name",
    category: "web3" as const,
    label: "Blockchain",
    icon: "⛓",
    placeholder: "Ethereum",
    description: "Blockchain network name",
    inputType: "select" as const,
    validation: {
      options: [
        "Ethereum",
        "Bitcoin",
        "Solana",
        "Polygon",
        "Arbitrum",
        "Optimism",
        "Base",
        "Avalanche",
        "BSC",
        "Other",
      ],
    },
    autoFill: "chain-name" as const,
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "nft-id": {
    id: "nft-id",
    category: "web3" as const,
    label: "NFT / Token ID",
    icon: "🖼",
    placeholder: "#1234",
    description: "NFT token ID",
    inputType: "text" as const,
    color: {
      border: "border-rose-400/50",
      bg: "bg-rose-400/10",
      text: "text-rose-400",
      glow: "shadow-[0_0_16px_rgba(251,113,133,0.2)]",
    },
  },
  "dao-name": {
    id: "dao-name",
    category: "web3" as const,
    label: "DAO Name",
    icon: "🏛",
    placeholder: "MakerDAO",
    description: "Decentralized Autonomous Organization name",
    inputType: "text" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
};

// ─── Legal / Date Fields ─────────────────────────────────────────────────────

const LEGAL_FIELDS = {
  date: {
    id: "date",
    category: "legal" as const,
    label: "Date",
    icon: "📅",
    placeholder: "MM/DD/YYYY",
    description: "Date field",
    inputType: "date" as const,
    autoFill: "current-date" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "effective-date": {
    id: "effective-date",
    category: "legal" as const,
    label: "Effective Date",
    icon: "📅",
    placeholder: "MM/DD/YYYY",
    description: "Date the agreement becomes effective",
    inputType: "date" as const,
    autoFill: "current-date" as const,
    color: {
      border: "border-orange-400/50",
      bg: "bg-orange-400/10",
      text: "text-orange-400",
      glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    },
  },
  "expiration-date": {
    id: "expiration-date",
    category: "legal" as const,
    label: "Expiration Date",
    icon: "⏰",
    placeholder: "MM/DD/YYYY",
    description: "Date the agreement expires",
    inputType: "date" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "renewal-date": {
    id: "renewal-date",
    category: "legal" as const,
    label: "Renewal Date",
    icon: "🔁",
    placeholder: "MM/DD/YYYY",
    description: "Automatic renewal or extension date",
    inputType: "date" as const,
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "term-length": {
    id: "term-length",
    category: "legal" as const,
    label: "Term Length",
    icon: "📏",
    placeholder: "24 months",
    description: "Duration of the agreement",
    inputType: "text" as const,
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "notice-period": {
    id: "notice-period",
    category: "legal" as const,
    label: "Notice Period",
    icon: "⏳",
    placeholder: "30 days",
    description: "Required advance notice period",
    inputType: "text" as const,
    validation: { maxLength: 30 },
    color: {
      border: "border-orange-300/50",
      bg: "bg-orange-300/10",
      text: "text-orange-300",
      glow: "shadow-[0_0_16px_rgba(253,186,116,0.15)]",
    },
  },
  "contract-id": {
    id: "contract-id",
    category: "legal" as const,
    label: "Contract ID",
    icon: "#",
    placeholder: "CTR-2026-0001",
    description: "Internal contract or agreement identifier",
    inputType: "text" as const,
    validation: { maxLength: 50 },
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  jurisdiction: {
    id: "jurisdiction",
    category: "legal" as const,
    label: "Governing Jurisdiction",
    icon: "⚖",
    placeholder: "State of Delaware, USA",
    description: "Legal jurisdiction that governs the agreement",
    inputType: "text" as const,
    color: {
      border: "border-amber-500/50",
      bg: "bg-amber-500/10",
      text: "text-amber-500",
      glow: "shadow-[0_0_16px_rgba(245,158,11,0.2)]",
    },
  },
  "governing-law": {
    id: "governing-law",
    category: "legal" as const,
    label: "Governing Law",
    icon: "📕",
    placeholder: "Laws of the State of...",
    description: "Which body of law governs the agreement",
    inputType: "text" as const,
    color: {
      border: "border-amber-500/50",
      bg: "bg-amber-500/10",
      text: "text-amber-500",
      glow: "shadow-[0_0_16px_rgba(245,158,11,0.2)]",
    },
  },
  "witness-name": {
    id: "witness-name",
    category: "legal" as const,
    label: "Witness Name",
    icon: "👁",
    placeholder: "Witness full name",
    description: "Name of witness to the signing",
    inputType: "text" as const,
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "notary-field": {
    id: "notary-field",
    category: "legal" as const,
    label: "Notary Public",
    icon: "🪪",
    placeholder: "Notary name and commission #",
    description: "Notary public details",
    inputType: "text" as const,
    color: {
      border: "border-slate-400/50",
      bg: "bg-slate-400/10",
      text: "text-slate-400",
      glow: "shadow-[0_0_16px_rgba(148,163,184,0.2)]",
    },
  },
  "clause-number": {
    id: "clause-number",
    category: "legal" as const,
    label: "Clause Reference",
    icon: "§",
    placeholder: "Section 4.2(b)",
    description: "Reference to a specific clause or section",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
};

// ─── Verification Fields ─────────────────────────────────────────────────────

const VERIFICATION_FIELDS = {
  "acknowledge-checkbox": {
    id: "acknowledge-checkbox",
    category: "verification" as const,
    label: "Acknowledgment",
    icon: "☑",
    placeholder: "I acknowledge and agree",
    description: "Checkbox requiring explicit acknowledgment",
    inputType: "checkbox" as const,
    color: {
      border: "border-yellow-400/50",
      bg: "bg-yellow-400/10",
      text: "text-yellow-400",
      glow: "shadow-[0_0_16px_rgba(250,204,21,0.2)]",
    },
  },
  "risk-warning": {
    id: "risk-warning",
    category: "verification" as const,
    label: "Risk Acknowledgment",
    icon: "⚠",
    placeholder: "I understand and accept the risks",
    description: "Explicit risk disclosure acceptance (required for web3)",
    inputType: "checkbox" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "age-verification": {
    id: "age-verification",
    category: "verification" as const,
    label: "Age Verification (18+)",
    icon: "🔞",
    placeholder: "I confirm I am 18 years or older",
    description: "Legal age verification checkbox",
    inputType: "checkbox" as const,
    color: {
      border: "border-red-400/50",
      bg: "bg-red-400/10",
      text: "text-red-400",
      glow: "shadow-[0_0_16px_rgba(248,113,113,0.2)]",
    },
  },
  "twitter-handle": {
    id: "twitter-handle",
    category: "verification" as const,
    label: "X (Twitter) Handle",
    icon: "𝕏",
    placeholder: "@username",
    description: "Twitter/X username for social verification",
    inputType: "text" as const,
    prefix: "@",
    validation: { pattern: "^@?[\\w]{1,15}$" },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "discord-handle": {
    id: "discord-handle",
    category: "verification" as const,
    label: "Discord Username",
    icon: "💬",
    placeholder: "username#0000",
    description: "Discord username for verification",
    inputType: "text" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "telegram-handle": {
    id: "telegram-handle",
    category: "verification" as const,
    label: "Telegram Username",
    icon: "✈",
    placeholder: "@username",
    description: "Telegram username",
    inputType: "text" as const,
    prefix: "@",
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
  "github-handle": {
    id: "github-handle",
    category: "verification" as const,
    label: "GitHub Username",
    icon: "🐙",
    placeholder: "username",
    description: "GitHub username for developer verification",
    inputType: "text" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "id-verification": {
    id: "id-verification",
    category: "verification" as const,
    label: "ID Verification",
    icon: "🪪",
    placeholder: "Verify signer identity",
    description: "Run built-in algorithmic identity checks from signer-provided data",
    inputType: "idv" as const,
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },

  // ── OAuth-verified social fields (signer proves ownership via login) ──
  "x-verify": {
    id: "x-verify",
    category: "verification" as const,
    label: "Verify X (Twitter)",
    icon: "𝕏",
    placeholder: "Verify your X account",
    description: "Signer proves X/Twitter account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "github-verify": {
    id: "github-verify",
    category: "verification" as const,
    label: "Verify GitHub",
    icon: "🐙",
    placeholder: "Verify your GitHub account",
    description: "Signer proves GitHub account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.2)]",
    },
  },
  "discord-verify": {
    id: "discord-verify",
    category: "verification" as const,
    label: "Verify Discord",
    icon: "💬",
    placeholder: "Verify your Discord account",
    description: "Signer proves Discord account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-indigo-400/50",
      bg: "bg-indigo-400/10",
      text: "text-indigo-400",
      glow: "shadow-[0_0_16px_rgba(129,140,248,0.2)]",
    },
  },
  "google-verify": {
    id: "google-verify",
    category: "verification" as const,
    label: "Verify Google",
    icon: "🔵",
    placeholder: "Verify your Google account",
    description: "Signer proves Google account ownership via OAuth login",
    inputType: "social-verify" as const,
    color: {
      border: "border-blue-400/50",
      bg: "bg-blue-400/10",
      text: "text-blue-400",
      glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    },
  },
};

// ─── Signature Fields ────────────────────────────────────────────────────────

const SIGNATURE_FIELDS = {
  signature: {
    id: "signature",
    category: "signature" as const,
    label: "Signature",
    icon: "✍",
    placeholder: "Draw your signature",
    description: "Hand-drawn or typed signature",
    inputType: "signature" as const,
    color: {
      border: "border-emerald-400/50",
      bg: "bg-emerald-400/10",
      text: "text-emerald-400",
      glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    },
  },
  initials: {
    id: "initials",
    category: "signature" as const,
    label: "Initials",
    icon: "✏",
    placeholder: "J.S.",
    description: "Your initials (for clause acknowledgment)",
    inputType: "initials" as const,
    validation: { maxLength: 5 },
    color: {
      border: "border-emerald-300/50",
      bg: "bg-emerald-300/10",
      text: "text-emerald-300",
      glow: "shadow-[0_0_16px_rgba(110,231,183,0.15)]",
    },
  },
};

// ─── Document / Structural Fields ────────────────────────────────────────────

const DOCUMENT_FIELDS = {
  "free-text": {
    id: "free-text",
    category: "document" as const,
    label: "Free Text",
    icon: "📝",
    placeholder: "Enter text...",
    description: "Open text field for custom input",
    inputType: "textarea" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  url: {
    id: "url",
    category: "document" as const,
    label: "URL",
    icon: "🔗",
    placeholder: "https://example.com",
    description: "Generic URL or link field",
    inputType: "url" as const,
    autoComplete: "url",
    validation: { pattern: "^https?://" },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  dropdown: {
    id: "dropdown",
    category: "document" as const,
    label: "Dropdown Select",
    icon: "▾",
    placeholder: "Select an option",
    description: "Dropdown with predefined choices",
    inputType: "select" as const,
    validation: { options: ["Option A", "Option B", "Option C"] },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  "radio-group": {
    id: "radio-group",
    category: "document" as const,
    label: "Radio Choices",
    icon: "◉",
    placeholder: "Choose one",
    description: "Single-choice radio options",
    inputType: "radio" as const,
    validation: { options: ["Yes", "No"] },
    color: {
      border: "border-sky-400/50",
      bg: "bg-sky-400/10",
      text: "text-sky-400",
      glow: "shadow-[0_0_16px_rgba(56,189,248,0.2)]",
    },
  },
  number: {
    id: "number",
    category: "document" as const,
    label: "Number",
    icon: "#",
    placeholder: "0",
    description: "Numeric value",
    inputType: "number" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  time: {
    id: "time",
    category: "document" as const,
    label: "Time",
    icon: "🕒",
    placeholder: "09:30",
    description: "Time of day",
    inputType: "time" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  datetime: {
    id: "datetime",
    category: "document" as const,
    label: "Date & Time",
    icon: "🗓",
    placeholder: "MM/DD/YYYY 09:30",
    description: "Combined date and time value",
    inputType: "datetime-local" as const,
    color: {
      border: "border-gray-400/50",
      bg: "bg-gray-400/10",
      text: "text-gray-400",
      glow: "shadow-[0_0_16px_rgba(156,163,175,0.15)]",
    },
  },
  "file-attachment": {
    id: "file-attachment",
    category: "document" as const,
    label: "File Attachment",
    icon: "📎",
    placeholder: "Upload a file",
    description: "Attach a supporting document or image",
    inputType: "file" as const,
    color: {
      border: "border-zinc-400/50",
      bg: "bg-zinc-400/10",
      text: "text-zinc-400",
      glow: "shadow-[0_0_16px_rgba(161,161,170,0.15)]",
    },
  },
  "custom-field": {
    id: "custom-field",
    category: "document" as const,
    label: "Custom Field",
    icon: "✨",
    placeholder: "Configure custom input",
    description: "Build your own field with custom input type, validation, logic, badge, and visuals",
    inputType: "text" as const,
    color: {
      border: "border-fuchsia-400/50",
      bg: "bg-fuchsia-400/10",
      text: "text-fuchsia-400",
      glow: "shadow-[0_0_16px_rgba(232,121,249,0.2)]",
    },
  },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// UNIFIED REGISTRY
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const FIELD_REGISTRY = {
  ...IDENTITY_FIELDS,
  ...CONTACT_FIELDS,
  ...ADDRESS_FIELDS,
  ...FINANCIAL_FIELDS,
  ...WEB3_FIELDS,
  ...LEGAL_FIELDS,
  ...VERIFICATION_FIELDS,
  ...SIGNATURE_FIELDS,
  ...DOCUMENT_FIELDS,
} as const;

// Grouped for the toolbar/picker UI
export const FIELD_CATEGORIES: Array<{ id: FieldCategory; label: string; icon: string; fields: FieldTypeId[] }> = [
  {
    id: "identity",
    label: "Identity",
    icon: "👤",
    fields: [
      "full-name",
      "first-name",
      "middle-name",
      "last-name",
      "preferred-name",
      "company-name",
      "job-title",
      "tax-id",
      "ssn",
      "ssn-full",
      "dob",
      "passport-number",
      "drivers-license",
      "national-id",
      "nationality",
    ],
  },
  {
    id: "contact",
    label: "Contact",
    icon: "✉",
    fields: ["email", "secondary-email", "phone", "fax-number", "website", "linkedin-url"],
  },
  {
    id: "address",
    label: "Address",
    icon: "🏠",
    fields: [
      "street-address",
      "address-line-2",
      "billing-address",
      "mailing-address",
      "full-address",
      "city",
      "county",
      "state",
      "zip",
      "country",
    ],
  },
  {
    id: "financial",
    label: "Financial",
    icon: "💲",
    fields: [
      "currency-amount",
      "percentage",
      "bank-account",
      "account-holder-name",
      "routing-number",
      "credit-card-number",
      "cardholder-name",
      "credit-card-expiry",
      "credit-card-cvc",
      "billing-zip",
      "iban",
      "swift-bic",
      "invoice-number",
      "purchase-order",
      "payment-request",
    ],
  },
  {
    id: "web3",
    label: "Web3",
    icon: "🔐",
    fields: [
      "wallet-address",
      "eth-address",
      "btc-address",
      "sol-address",
      "ens-name",
      "token-amount",
      "tx-hash",
      "smart-contract",
      "chain-name",
      "nft-id",
      "dao-name",
    ],
  },
  {
    id: "legal",
    label: "Legal",
    icon: "⚖",
    fields: [
      "date",
      "effective-date",
      "expiration-date",
      "renewal-date",
      "term-length",
      "notice-period",
      "jurisdiction",
      "governing-law",
      "witness-name",
      "notary-field",
      "clause-number",
      "contract-id",
    ],
  },
  {
    id: "verification",
    label: "Verify",
    icon: "☑",
    fields: [
      "acknowledge-checkbox",
      "risk-warning",
      "age-verification",
      "twitter-handle",
      "discord-handle",
      "telegram-handle",
      "github-handle",
      "id-verification",
      "x-verify",
      "github-verify",
      "discord-verify",
      "google-verify",
    ],
  },
  { id: "signature", label: "Sign", icon: "✍", fields: ["signature", "initials"] },
  {
    id: "document",
    label: "Other",
    icon: "📝",
    fields: [
      "free-text",
      "url",
      "dropdown",
      "radio-group",
      "number",
      "time",
      "datetime",
      "file-attachment",
      "custom-field",
    ],
  },
];

export function getField(id: string): FieldConfig | undefined {
  return (FIELD_REGISTRY as Record<string, FieldConfig>)[id];
}

// Signer-based coloring: each signer gets a distinct color regardless of field type
export const SIGNER_COLORS = [
  {
    bg: "bg-blue-400/10",
    border: "border-blue-400/50",
    text: "text-blue-400",
    ring: "ring-blue-400/30",
    glow: "shadow-[0_0_16px_rgba(96,165,250,0.2)]",
    dot: "bg-blue-400",
  },
  {
    bg: "bg-orange-400/10",
    border: "border-orange-400/50",
    text: "text-orange-400",
    ring: "ring-orange-400/30",
    glow: "shadow-[0_0_16px_rgba(251,146,60,0.2)]",
    dot: "bg-orange-400",
  },
  {
    bg: "bg-purple-400/10",
    border: "border-purple-400/50",
    text: "text-purple-400",
    ring: "ring-purple-400/30",
    glow: "shadow-[0_0_16px_rgba(192,132,252,0.2)]",
    dot: "bg-purple-400",
  },
  {
    bg: "bg-emerald-400/10",
    border: "border-emerald-400/50",
    text: "text-emerald-400",
    ring: "ring-emerald-400/30",
    glow: "shadow-[0_0_16px_rgba(52,211,153,0.2)]",
    dot: "bg-emerald-400",
  },
  {
    bg: "bg-pink-400/10",
    border: "border-pink-400/50",
    text: "text-pink-400",
    ring: "ring-pink-400/30",
    glow: "shadow-[0_0_16px_rgba(244,114,182,0.2)]",
    dot: "bg-pink-400",
  },
  {
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/50",
    text: "text-cyan-400",
    ring: "ring-cyan-400/30",
    glow: "shadow-[0_0_16px_rgba(34,211,238,0.2)]",
    dot: "bg-cyan-400",
  },
] as const;

export type SignerColor = (typeof SIGNER_COLORS)[number];

export function getSignerColor(signerIndex: number): SignerColor {
  return SIGNER_COLORS[signerIndex % SIGNER_COLORS.length]!;
}
