export const FORENSIC_PROFILE_THRESHOLDS = {
  typing: {
    botCvMax: 0.15,
    botAvgDelayMsMax: 50,
    humanCvMin: 0.25,
    humanAutocorrelationMin: 0.1,
    botAutocorrelationAbsMax: 0.08,
  },
  signature: {
    syntheticUniformityMin: 0.82,
    syntheticVelocityCvMax: 0.18,
    syntheticDirectionChangesMax: 2,
    humanComplexityMin: 0.45,
    humanVelocityCvMin: 0.22,
    humanDirectionChangesMin: 3,
  },
  gaze: {
    naturalFixationCountMin: 5,
    naturalAvgFixationMsMin: 140,
    naturalAvgFixationMsMax: 900,
    naturalFixationCvMin: 0.18,
    naturalBlinkRateMin: 6,
    naturalBlinkRateMax: 30,
    naturalCoverageMin: 0.35,
    naturalReadingScoreMin: 0.3,
    syntheticPointCountMin: 30,
    syntheticNoBlinkPointCountMin: 60,
    syntheticFastFixationMsMax: 80,
    syntheticFixationCvMax: 0.08,
    syntheticReadingScoreMax: 0.08,
    syntheticAnchorHitRatioMax: 0.05,
    weakCoverageMax: 0.25,
    weakConfidenceAvgMax: 0.3,
  },
  liveness: {
    minPassRatio: 0.25,
    minHumanPassRatio: 0.25,
    suspiciousAverageReactionMs: 5000,
    suspiciousFailedSteps: 4,
    targetRadius: 0.30,
    targetHoldMs: 150,
    stepTimeoutMs: 10000,
  },
  baseline: {
    minSamples: 1,
    preferredSamples: 2,
    zScoreDeviationMin: 2.2,
    relativeDeviationMin: 0.45,
  },
} as const;
