#!/usr/bin/env node
/**
 * materialize-premium.mjs
 *
 * Generates the premium bridge layer at src/generated/premium/.
 *
 * When premium/ exists (and PROOFMARK_PREMIUM !== "0"):
 *   → bridge files re-export real premium modules.
 * When premium/ is absent (or --force-stubs):
 *   → bridge files export no-op stubs.
 *
 * Usage:
 *   node scripts/materialize-premium.mjs              # auto-detect
 *   node scripts/materialize-premium.mjs --force-stubs # always generate stubs
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "generated", "premium");
const PREMIUM_EXISTS =
  existsSync(join(ROOT, "premium", "index.ts")) &&
  process.env.PROOFMARK_PREMIUM !== "0";
const FORCE_STUBS = process.argv.includes("--force-stubs");
const PREMIUM = PREMIUM_EXISTS && !FORCE_STUBS;

const HEADER =
  "// AUTO-GENERATED by scripts/materialize-premium.mjs — DO NOT EDIT\n";

// Clean previous output
if (existsSync(OUT)) rmSync(OUT, { recursive: true });

function write(relPath, content) {
  const full = join(OUT, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, HEADER + content + "\n");
}

// ── Client-side page bridges ────────────────────────────────────────────────
const pages = [
  {
    file: "pages/escrow-dashboard.tsx",
    real: "../../../../premium/pages/escrow/page",
  },
  {
    file: "pages/escrow-create.tsx",
    real: "../../../../premium/pages/escrow/create/page",
  },
  {
    file: "pages/escrow-detail.tsx",
    real: "../../../../premium/pages/escrow/[id]/page",
  },
  {
    file: "pages/collab-session.tsx",
    real: "../../../../premium/pages/collab/[sessionId]/page",
  },
  {
    file: "pages/collab-invite.tsx",
    real: "../../../../premium/pages/collab/invite/[token]/page",
  },
  {
    file: "pages/collab-link.tsx",
    real: "../../../../premium/pages/collab/link/[token]/page",
  },
];

for (const { file, real } of pages) {
  if (PREMIUM) {
    write(file, `export { default } from "${real}";\n`);
  } else {
    write(file, `/* eslint-disable @typescript-eslint/no-explicit-any */\nexport default function PremiumStub(_props?: any) {\n  return null;\n}\n`);
  }
}

// ── Client-side component bridges ───────────────────────────────────────────
const components = [
  {
    file: "components/collab-toolbar.tsx",
    real: "../../../../premium/components/collab/collab-toolbar",
    named: "CollabToolbar",
  },
  {
    file: "components/collab-annotations.tsx",
    real: "../../../../premium/components/collab/collab-annotations",
    named: "CollabAnnotationSidebar",
  },
  {
    file: "components/collab-ai-panel.tsx",
    real: "../../../../premium/components/collab/collab-ai-panel",
    named: "CollabAiPanel",
  },
  {
    file: "components/collab-share-popover.tsx",
    real: "../../../../premium/components/collab/collab-share-popover",
    named: "CollabSharePopover",
  },
  {
    file: "components/ai-provider-settings.tsx",
    real: "../../../../premium/components/ai/ai-provider-settings",
    named: "AiProviderSettings",
  },
];

for (const { file, real, named } of components) {
  if (PREMIUM) {
    write(file, `export { ${named} as default } from "${real}";\n`);
  } else {
    write(
      file,
      `/* eslint-disable @typescript-eslint/no-explicit-any */\nexport default function PremiumStub(_props?: any) {\n  return null;\n}\n`,
    );
  }
}

// ── Server-side TypeScript stubs ────────────────────────────────────────────
// These serve as tsconfig path fallback when premium/ is absent.
// In premium builds, TypeScript resolves ~/premium/* to ./premium/* directly
// and never reaches these files.

write(
  "ai/automation-review.ts",
  `/* eslint-disable @typescript-eslint/no-explicit-any */
export function reviewAutomationEvidence(..._args: any[]): any {
  throw new Error("Premium module not available");
}
`,
);

write(
  "ai/key-resolver.ts",
  `/* eslint-disable @typescript-eslint/no-explicit-any */
export function getPlatformProviders(): any[] {
  return [];
}
export function readPlatformEnv(_provider: string): any {
  return {};
}
`,
);

write(
  "ai/forensic-queue.ts",
  `export function enqueueAiForensicReview(
  _signerId: string,
  _documentId: string,
): void {}
`,
);

// ── Index marker ────────────────────────────────────────────────────────────
write(
  "index.ts",
  `export const PREMIUM_SURFACE_MODE = ${JSON.stringify(PREMIUM ? "premium" : "oss")} as const;
`,
);

const mode = PREMIUM ? "PREMIUM (re-exports)" : "OSS (stubs)";
console.log(
  `[materialize] Generated premium surface at src/generated/premium/ [${mode}]`,
);
