#!/usr/bin/env node
/**
 * materialize-premium.mjs
 *
 * Generates the premium bridge layer at src/generated/premium/.
 *
 * When premium/ exists (and PROOFMARK_PREMIUM !== "0"):
 *   → bridge files re-export real premium modules.
 * When premium/ is absent (or --force-stubs):
 *   → bridge files export no-op stubs.
 *
 * Usage:
 *   node scripts/materialize-premium.mjs              # auto-detect
 *   node scripts/materialize-premium.mjs --force-stubs # always generate stubs
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "generated", "premium");
const PREMIUM_EXISTS =
	existsSync(join(ROOT, "premium", "index.ts")) &&
	process.env.PROOFMARK_PREMIUM !== "0";
const FORCE_STUBS = process.argv.includes("--force-stubs");
const PREMIUM = PREMIUM_EXISTS && !FORCE_STUBS;

const HEADER =
	"// AUTO-GENERATED by scripts/materialize-premium.mjs — DO NOT EDIT\n";

// Clean previous output
if (existsSync(OUT)) rmSync(OUT, { recursive: true });

function write(relPath, content) {
	const full = join(OUT, relPath);
	mkdirSync(dirname(full), { recursive: true });
	writeFileSync(full, HEADER + content + "\n");
}

// ── Client-side page bridges ────────────────────────────────────────────────
const pages = [
	{
		file: "pages/escrow-dashboard.tsx",
		real: "../../../../premium/pages/escrow/page",
	},
	{
		file: "pages/escrow-create.tsx",
		real: "../../../../premium/pages/escrow/create/page",
	},
	{
		file: "pages/escrow-detail.tsx",
		real: "../../../../premium/pages/escrow/[id]/page",
	},
	{
		file: "pages/collab-session.tsx",
		real: "../../../../premium/pages/collab/[sessionId]/page",
	},
	{
		file: "pages/collab-invite.tsx",
		real: "../../../../premium/pages/collab/invite/[token]/page",
	},
	{
		file: "pages/collab-link.tsx",
		real: "../../../../premium/pages/collab/link/[token]/page",
	},
];

for (const { file, real } of pages) {
	if (PREMIUM) {
		write(file, `export { default } from "${real}";\n`);
	} else {
		write(
			file,
			`export default function PremiumStub(_props?: Record<string, unknown>) {\n  return null;\n}\n`,
		);
	}
}

// ── Client-side component bridges ───────────────────────────────────────────
const components = [
	{
		file: "components/collab-toolbar.tsx",
		real: "../../../../premium/components/collab/collab-toolbar",
		named: "CollabToolbar",
	},
	{
		file: "components/collab-annotations.tsx",
		real: "../../../../premium/components/collab/collab-annotations",
		named: "CollabAnnotationSidebar",
	},
	{
		file: "components/collab-ai-panel.tsx",
		real: "../../../../premium/components/collab/collab-ai-panel",
		named: "CollabAiPanel",
	},
	{
		file: "components/collab-share-popover.tsx",
		real: "../../../../premium/components/collab/collab-share-popover",
		named: "CollabSharePopover",
	},
	{
		file: "components/ai-provider-settings.tsx",
		real: "../../../../premium/components/ai/ai-provider-settings",
		named: "AiProviderSettings",
	},
];

for (const { file, real, named } of components) {
	if (PREMIUM) {
		write(file, `export { ${named} as default } from "${real}";\n`);
	} else {
		write(
			file,
			`export default function PremiumStub(_props?: Record<string, unknown>) {\n  return null;\n}\n`,
		);
	}
}

// ── Server-side AI module bridges ────────────────────────────────────────────
// In premium: re-exports from real modules. In OSS: typed Zod stubs.
// Consuming code imports from ~/generated/premium/ai/* so eslint can
// resolve types through the standard ~/* path.

if (PREMIUM) {
	write(
		"ai/automation-review.ts",
		`export { reviewAutomationEvidence } from "../../../../premium/ai/automation-review";
export type { AutomationReviewResult } from "../../../../premium/ai/automation-review";
`,
	);
	write(
		"ai/key-resolver.ts",
		`export { getPlatformProviders, resolveKeyWithFallback } from "../../../../premium/ai/key-resolver";
export type { ResolvedKeyWithModel } from "../../../../premium/ai/key-resolver";
`,
	);
	write(
		"ai/forensic-queue.ts",
		`export { enqueueForensicReview } from "../../../../premium/ai/forensic-queue";
`,
	);
} else {
	write(
		"ai/automation-review.ts",
		`import { z } from "zod";

const reviewSchema = z.object({
  verdict: z.string(),
  confidence: z.number(),
  automationScore: z.number(),
  signals: z.array(z.unknown()).optional(),
});

export interface AutomationReviewResult {
  review: z.infer<typeof reviewSchema>;
  usage: { inputTokens: number; outputTokens: number; model: string };
}

export async function reviewAutomationEvidence(
  _params: Record<string, unknown>,
): Promise<AutomationReviewResult> {
  throw new Error("Premium module not available");
}
`,
	);

	write(
		"ai/key-resolver.ts",
		`import { z } from "zod";

const providerSchema = z.object({
  provider: z.string(),
  available: z.boolean(),
  label: z.string(),
  defaultModel: z.string(),
});

export interface ResolvedKeyWithModel {
  key: {
    apiKey: string;
    source: string;
    provider: string;
    ownerAddress?: string;
    baseUrl?: string;
    organizationId?: string;
  };
  model: string;
}

export function getPlatformProviders(): z.infer<typeof providerSchema>[] {
  return [];
}

export async function resolveKeyWithFallback(
  _ownerAddress: string,
  _provider: string,
): Promise<ResolvedKeyWithModel | null> {
  return null;
}
`,
	);

	write(
		"ai/forensic-queue.ts",
		`export function enqueueForensicReview(_params: {
  signerId: string;
  documentId: string;
}): void {}
`,
	);
}

// ── Billing component bridges ───────────────────────────────────────────────
const billingComponents = [
	{
		file: "components/billing/crypto-billing-settings.tsx",
		real: "../../../../premium/components/billing/crypto-billing-settings",
		named: "CryptoBillingSettings",
	},
	{
		file: "components/billing/use-crypto-subscription.ts",
		real: "../../../../premium/components/billing/use-crypto-subscription",
		named: "useCryptoSubscription",
	},
];

for (const { file, real, named } of billingComponents) {
	if (PREMIUM) {
		write(file, `// @ts-ignore -- premium module path resolved at runtime\nexport { ${named} as default } from "${real}";\n`);
	} else {
		if (file.endsWith(".tsx")) {
			write(
				file,
				`export default function PremiumStub(_props?: Record<string, unknown>) {\n  return null;\n}\n`,
			);
		} else {
			write(
				file,
				`export default function useCryptoSubscription() {\n  return { available: false, subscribe: async () => {}, cancel: async () => {} };\n}\n`,
			);
		}
	}
}

// ── Server-side billing module bridges ──────────────────────────────────────
if (PREMIUM) {
	write(
		"billing/ai-billing.ts",
		`// @ts-ignore -- premium module path resolved at runtime via tsconfig paths
export { checkAiUsageAllowance, recordAiUsage, getMonthlyAiUsageSummary } from "../../../../premium/billing/ai-billing";
`,
	);
	write(
		"billing/hash-anchor-service.ts",
		`// @ts-ignore -- premium module path resolved at runtime via tsconfig paths
export { enqueueHash, verifyHash, flushBatch, startFlushTimer, stopFlushTimer } from "../../../../premium/billing/hash-anchor-service";
`,
	);
} else {
	write(
		"billing/ai-billing.ts",
		`export async function checkAiUsageAllowance(_ownerAddress: string) {
  return { allowed: true, remainingTokens: Number.MAX_SAFE_INTEGER, overageRate: 0, model: "unlimited" as const };
}
export async function recordAiUsage(_params: { ownerAddress: string; inputTokens: number; outputTokens: number }) {}
export async function getMonthlyAiUsageSummary(_ownerAddress: string, _month?: string) {
  return { inputTokensUsed: 0, outputTokensUsed: 0, bundleLimit: 0, overageTokens: 0, overageCostCents: 0, model: "unlimited" as const };
}
`,
	);
	write(
		"billing/hash-anchor-service.ts",
		`export async function enqueueHash(_documentHash: string) {
  throw new Error("Premium module not available");
}
export async function verifyHash(_documentHash: string) {
  return { anchored: false, timestamp: 0, anchorer: "" };
}
export async function flushBatch() {}
export function startFlushTimer() {}
export function stopFlushTimer() {}
`,
	);
}

// ── Server-side router bridges ──────────────────────────────────────────────
const serverRouters = [
	{
		file: "server/routers/ai.ts",
		real: "../../../../../premium/server/routers/ai",
		named: "aiRouter",
	},
	{
		file: "server/routers/billing.ts",
		real: "../../../../../premium/server/routers/billing",
		named: "billingPremiumRouter",
	},
	{
		file: "server/routers/collab.ts",
		real: "../../../../../premium/server/routers/collab",
		named: "collabRouter",
	},
	{
		file: "server/routers/connector.ts",
		real: "../../../../../premium/server/routers/connector",
		named: "connectorRouter",
	},
	{
		file: "server/routers/escrow.ts",
		real: "../../../../../premium/server/routers/escrow",
		named: "escrowRouter",
	},
	{
		file: "server/routers/runtime.ts",
		real: "../../../../../premium/server/routers/runtime",
		named: "runtimeRouter",
	},
];

for (const { file, real, named } of serverRouters) {
	if (PREMIUM) {
		write(file, `export { ${named} } from "${real}";\n`);
	} else {
		write(file, `export const ${named} = null;\n`);
	}
}

// ── Index marker ────────────────────────────────────────────────────────────
write(
	"index.ts",
	`export const PREMIUM_SURFACE_MODE = ${JSON.stringify(PREMIUM ? "premium" : "oss")} as const;
`,
);

const mode = PREMIUM ? "PREMIUM (re-exports)" : "OSS (stubs)";
console.log(
	`[materialize] Generated premium surface at src/generated/premium/ [${mode}]`,
);
