import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    PDF_UPLOAD_MAX_MB: z.coerce.number().int().positive().default(10),
    SMTP_HOST: z.string().default(""),
    SMTP_PORT: z.coerce.number().default(465),
    SMTP_USER: z.string().default(""),
    SMTP_PASS: z.string().default(""),
    SMTP_FROM: z.string().default("noreply@proofmark.local"),
    ADMIN_EMAIL: z.string().default(""),
    PROXY_API_URL: z.string().default("http://192.168.1.24:8081"),
    OWNER_ADDRESS: z.string().default(""),
    OWNER_CHAIN: z.string().default("ETH"),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    ENCRYPTION_MASTER_KEY: z.string().min(32).optional(),
    AUTOMATION_SECRET: z.string().default(""),
    BETTER_AUTH_SECRET: z.string().default(""),
    BETTER_AUTH_URL: z.string().default(""),
    PROOFMARK_DEPLOYMENT_MODE: z.enum(["oss", "premium"]).default("oss"),
  },
  client: {},
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    PDF_UPLOAD_MAX_MB: process.env.PDF_UPLOAD_MAX_MB,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_FROM: process.env.SMTP_FROM,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    PROXY_API_URL: process.env.PROXY_API_URL,
    OWNER_ADDRESS: process.env.OWNER_ADDRESS,
    OWNER_CHAIN: process.env.OWNER_CHAIN,
    NODE_ENV: process.env.NODE_ENV,
    ENCRYPTION_MASTER_KEY: process.env.ENCRYPTION_MASTER_KEY,
    AUTOMATION_SECRET: process.env.AUTOMATION_SECRET,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    PROOFMARK_DEPLOYMENT_MODE: process.env.PROOFMARK_DEPLOYMENT_MODE,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
